### PR TITLE
fix linking rt for glibc versions before 2.17

### PR DESCRIPTION
**Pull request by guzhou2022**
https://github.com/linux-test-project/ltp/issues/997

### CODE REVIEW

**Comment by metan-ucw** [comment]
The changes looks good, however the commits are missing Signed-off-by line see: https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Comment by metan-ucw** [comment]
Can you please update the commit descriptions and add the missing Signed-off-by lines so that we can merge these patches?

**Comment by guzhou2022** [comment]
Sorry, I will resubmit as soon as possible

**Comment by pevik** [comment]
Or just post here your real name and email and we will add it and merge.

**Comment by guzhou2022** [comment]
**fix linking rt for glibc versions before 2.17**

According to the manual page of clock_gettime(3), we should link with -lrt (only for glibc versions before 2.17).
For glibc after 2.17, explicit linking with -lrt has no effect.

Signed-off-by: Ci Zhou <zhouci@ruijie.com.cn>

**Comment by pevik** [comment]
Merged, thank you!

**Pull request closed without merging**
