### PR TITLE
open_posix_testsuite: fix out-of-build-tree on Linux

### PR DESCRIPTION
**Pull request by cavokz**
Signed-off-by: Domenico Andreoli <domenico.andreoli@linux.com>

### CODE REVIEW

**Comment by cavokz** [comment]
will reopen later

**Comment by pevik** [comment]
@cavokz are you still working on this? As I'm working on it as well...

**Comment by cavokz** [comment]
@pevik no, not at the moment but I've some scars and would be a pity to waste them. did you look at my changes, are you thinking to reuse anything?

**Comment by pevik** [comment]
@cavokz thanks for info. Although there is some similarity in our patches, I took a bit different approach as I've already had my patch before I noticed this ticket (most of development happens on mailing list [1], it's better to post patches there). Here is my patch http://lists.linux.it/pipermail/ltp/2017-April/004218.html.

I'm going to rewrite open_posix_testsuite installation part as installing data directories directly into `/opt/ltp` isn't optimal.

Anyway, thanks your time and effort spent on this issue.

[1]: https://lists.linux.it/listinfo/ltp

**Comment by cavokz** [comment]
@pevik I'll check what was in my patches to see if miss anything ;)
I'll tune to the ml later. thanks.

**Pull request closed without merging**
