### PR TITLE
Fix fcntl31

### PR DESCRIPTION
**Pull request by sgwlf**
[ type description here; PLEASE REMOVE THIS LINE AND THE LINES BELOW BEFORE SUBMITTING THIS PULL REQUEST ]

### CODE REVIEW

**Comment by sgwlf** [comment]
fixup fcntl31  interface test

**Review by metan-ucw — COMMENTED** [review]
As far as I can tell the orig_own_ex is initialized in the test setup() and is used to reset the value back after each test. It does not make any sense to set this to the tst_own_ex.

**Review by metan-ucw — COMMENTED** [review]
And what is wrong with the default user group ID here? It's used by the test to reset the value back after each test and I do not see anything wrong with that.

**Comment by sgwlf** [comment]
Sorry, I misunderstood.

**Pull request closed without merging**
