### PR TITLE
Fix installation instructions.

### PR DESCRIPTION
**Pull request by tfjmp**
git clone https://github.com/linux-test-project/ltp.git -> git clone https://github.com/the-linux-test-project/ltp.git

### CODE REVIEW

**Comment by pevik** [comment]
LGTM :+1: 
Please could you just add the signed-off-by line to the commit message?

**Comment by tfjmp** [comment]
Ah sorry, added the signed-off line.

**Comment by vapier** [comment]
your git commit message is inverted

**Comment by tfjmp** [comment]
Should be good this time.

**Comment by vapier** [comment]
thanks!

**Pull request merged**
