### PR TITLE
Remove the cleanup function since it is empty.

### PR DESCRIPTION
**Pull request by sunyuan3**
The action is suggestted by Cyril Hrubis.

Signed-off-by: Yuan Sun <sunyuan3@huawei.com>

### CODE REVIEW

**Comment by sunyuan3** [comment]
This PR is suggested by metan-ucw.
https://github.com/linux-test-project/ltp/pull/39

ping @metan-ucw

**Comment by vapier** [comment]
there are many pidns testcases that can get cleaned up like this.  please do it to all of them.

**Comment by sunyuan3** [comment]
Hi vapier ,
I do it to all of pidns testcases.

**Comment by vapier** [comment]
thanks; merged !

**Pull request merged**
