### PR TITLE
update legacy codes in ltp_tpci.c

### PR DESCRIPTION
**Pull request by FirstLoveLife**

### CODE REVIEW

**Comment by pevik** [comment]
This is obviously correct, but I cannot merge it as you didn't put your `Signed-off-by:` tag to the commit. That would be enough for me to finish your effort :).

BTW also somebody else is working on this as well: https://lists.linux.it/pipermail/ltp/2020-March/015846.html
\+ For next time: we prefer patches to our mailing list (all this is described in https://github.com/linux-test-project/ltp#developers-corner), but of course sent via `git send-email` (described in https://github.com/linux-test-project/ltp/wiki/C-Test-Case-Tutorial).

**Comment by pevik** [comment]
OK, patchset in ML was sent by you. But it's wrongly formatted, please see the docs I've sent.

**Comment by FirstLoveLife** [comment]
@pevik Thanks for reply! I have resent my patch to mail list just now.

**Comment by FirstLoveLife** [comment]
merged in master

**Pull request closed without merging**
