### PR TITLE
INSTALL fixups

### PR DESCRIPTION
**Pull request by mkow**
Building instructions from INSTALL didn't work due to a small mistake. I also slightly fixed up formatting in this file (in a separate commit).

### CODE REVIEW

**Comment by pevik** [comment]
Thanks for your fixes.
I personally don't like indented shell code, but no strong preference. Otherwise LGTM. Second commit is obviously correct.

To merge your commit we need your `Signed-off-by` tag (i.e. `Signed-off-by: Your Name <your_email>`. For next time: we prefer patches to be sent to our mailing list https://github.com/linux-test-project/ltp#developers-corner.

**Comment by mkow** [comment]
> I personally don't like indented shell code, but no strong preference.

I just tried to make the formatting consistent, as most other places in this file have shell listings indented. But I can drop this change if you prefer, no strong feelings here.

> To merge your commit we need your `Signed-off-by tag`

Hmm, what's the meaning of sign-offs in this project? I can't find a CLA or any sing-off information in the documentation / readmes.

> For next time: we prefer patches to be sent to our mailing list

Ok, I'll try next time, although I consider this workflow quite PITA ;)

**Comment by pevik** [comment]
> > I personally don't like indented shell code, but no strong preference.
> 
> I just tried to make the formatting consistent, as most other places in this file have shell listings indented. But I can drop this change if you prefer, no strong feelings here.

Let's keep it.

> 
> > To merge your commit we need your `Signed-off-by tag`
> 
> Hmm, what's the meaning of sign-offs in this project? I can't find a CLA or any sing-off information in the documentation / readmes.

Just put your name and email there, please. Meaning? https://www.kernel.org/doc/html/latest/process/submitting-patches.html

> > For next time: we prefer patches to be sent to our mailing list
> 
> Ok, I'll try next time, although I consider this workflow quite PITA ;)

Like it or not, LTP is based on Linux kernel development (using mailing list, patchwork, `Signed-off-by tag` etc). I'd myself prefer to move out of github (and use it as a mirror), but we decided to use github issues as our bug tracker.

**Comment by mkow** [comment]
> Just put your name and email there, please.

Done.

> Meaning? https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

Hmm, isn't sign-off tag meaning defined per-project? AFAIR different projects can have different meaning for this tag and my confusion was because you don't have any meaning defined in your docs (your link leads to Linux, not LTP docs). I'll assume I'm signing off DCO 1.1.

> Like it or not, LTP is based on Linux kernel development (using mailing list, patchwork, Signed-off-by tag etc). I'd myself prefer to move out of github (and use it as a mirror), but we decided to use github issues as our bug tracker.

Yeah, I noticed now, I'm just grumbling ;)

> NOTE: worth to read our wiki:
> https://github.com/linux-test-project/ltp/wiki/Test-Writing-Guidelines
> https://github.com/linux-test-project/ltp/wiki/C-Test-Case-Tutorial

I briefly looked at the Wiki before posting this PR, but "Test Writing Guidelines" and "C Test Case Tutorial" sounded like unrelated to this PR (which only modifies the documentation, I'm not writing a new test). I tried looking at https://github.com/linux-test-project/ltp/wiki/Developers, but all links except "Test Writing Guidelines" are broken there.

**Comment by metan-ucw** [comment]
We do follow Linux coding style as well, so I guess that adding a document that points to kernel documentation and checkpatch.pl is a good idea.

**Comment by pevik** [comment]
> I briefly looked at the Wiki before posting this PR, but "Test Writing Guidelines" and "C Test Case Tutorial" sounded like unrelated to this PR (which only modifies the documentation, I'm not writing a new test). I tried looking at https://github.com/linux-test-project/ltp/wiki/Developers, but all links except "Test Writing Guidelines" are broken there.

Thanks, after consultation with @metan-ucw I deleted Developers page (useless) and rewrote wiki homepage (https://github.com/linux-test-project/ltp/wiki) to contain relevant info (which is also in https://github.com/linux-test-project/ltp#developers-corner, but nobody sees it here). We should put there info about `Signed-off-by`.

**Comment by pevik** [comment]
@metan-ucw: checkpatch.pl is mentioned in https://github.com/linux-test-project/ltp/wiki/Test-Writing-Guidelines#13-coding-style. Maybe we should
* replace `linux/Documentation/CodingStyle` with https://www.kernel.org/doc/html/latest/process/coding-style.html#codingstyle link
* mention `Signed-off-by` with https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin link.
Maybe we could move content of Coding style part to its own (separate) page (and mention it in wiki homepage and at README.md).

**Comment by mkow** [comment]
Thanks for fixing the Wiki.

>  Maybe we could move content of Coding style part to its own (separate) page (and mention it in wiki homepage and at README.md).

+1 to this, but I'd also separate contributing guidelines (not only the code style). I haven't found this info before because I thought "Test Writing Guidelines" is only about "how to write a new test".

**Pull request closed without merging**
