### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bedi1982**
Just a typo fix.

### CODE REVIEW

**Comment by pevik** [comment]
LGTM

**Comment by metan-ucw** [comment]
Can you please include Signed-off-by: line in the commit description?

Otherwise it's obviously OK.

**Comment by richiejp** [comment]
@bedi1982 ping

Can you add signed off by line? Otherwise I guess we can make the change and credit you with finding it.

**Comment by metan-ucw** [comment]
This has been fixed in  #184

**Pull request closed without merging**
