### PR TITLE
Add userns01 testcase to verify user namespace.

### PR DESCRIPTION
**Pull request by sunyuan3**
Signed-off-by: Yuan Sun <sunyuan3@huawei.com>

### CODE REVIEW

**Comment by sunyuan3** [comment]
HI maintainers,
Could you please help me review the patch?
Any comment?

**Comment by gaowanlong** [comment]
Would you please send the patches to our LTP mail list(ltp-list@lists.sourceforge.net) for review?
Mail list is the prefer place to review and discuss with others.

Thanks,
Wanlong Gao

**Comment by sunyuan3** [comment]
Ok. Thanks for our suggestion. I will send the patches to the LTP mail list.

**Comment by metan-ucw** [comment]
For simple fixes pull requests are ok. But for new testcases, as Wanlong Gao said, it's better to post the patches to the mailing list as not all reviewers are commenting on github.

**Pull request closed without merging**
