### PR TITLE
utimensat_tests.sh: tst_brkm doesn't support TWARN

### PR DESCRIPTION
**Pull request by bentsi**
need to use TFAIL or TCONF

### CODE REVIEW

**Comment by metan-ucw** [comment]
Looking into the `testcases/lib/test.sh` which is included by the `utimensat_tests.sh` it does include `TWARN` in the tst_flag2mask() function. That is strange, this is supposed to work fine.

Can you please include the error message you have been seeing?

**Comment by bentsi** [comment]
@metan-ucw the function that is called in `utimensat_tests.sh` is `tst_brkm()` and NOT `tst_flag2mask()`

**Comment by metan-ucw** [comment]
@bentsi Ah right, we filter for `TFAIL`, `TBROK` and `TCONF` at the start of the `tst_brkm()` function even before we call `tst_resm()` which calls the `tst_flag2mask()`.

I guess that `TBROK` (something went wrong before the actual test) would be a bit more appropriate than `TFAIL` in this case. Or we can also drop the check completely, it does not look that useful to me anyway.

**Comment by metan-ucw** [comment]
Can you please merge these two patches into one and also add a Signed-off-by line to the commit message? The code change looks fine now.

**Comment by bentsi** [comment]
Done.

**Comment by metan-ucw** [comment]
I've fixed the commit description so that the signed-of-by line is on a separate line and pushed, thanks.

**Pull request closed without merging**
