### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Samarth-Gupta-2909**

### CODE REVIEW

**Comment by metan-ucw** [comment]
The change is obviously fine but the commit messages needs to be improved.

* It's missing Signed-off-by tag, see: 
  https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

* The description should be more descriptive, something as "Fix typo in README.md"

**Comment by Samarth-Gupta-2909** [comment]
Ok . Thanks for reviewing and helping . Actually it was first pull request in world of open source.

**Comment by metan-ucw** [comment]
Can you then, please, update the patch as I asked you to, so that I can apply it?

**Comment by metan-ucw** [comment]
Feel free to reopen with fixed patch.

**Pull request closed without merging**
